# Generated by Django 5.2.15 on 2026-06-23 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fac_name', models.TextField()),
                ('sub', models.TextField()),
                ('score', models.IntegerField()),
                ('email', models.TextField()),
            ],
        ),
    ]
