# Generated by Django 5.2.14 on 2026-05-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('roll', models.IntegerField()),
                ('mark', models.PositiveBigIntegerField()),
            ],
        ),
    ]
